# -*- coding: utf-8 -*-
"""AAPL part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seuUmDWIN9_pfJMap9PE6bOCaQnxW6_0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/drive/MyDrive/DV SKILL /AAPL.xlsx')

df.head()

df.tail()

df.shape

df.columns

df.info

plt.plot(df['Date'], df['Open'], label='Open')
plt.plot(df['Date'], df['High'], label='High')
plt.plot(df['Date'], df['Low'], label='Low')
plt.plot(df['Date'], df['Close'], label='Close')

plt.xlabel('Date')
plt.ylabel('Price')
plt.title('AAPL OHLC Prices')
plt.show()

plt.plot(df['Date'], df['Volume'])
plt.xlabel('Date')
plt.ylabel('Volume')
plt.title('AAPL Trading Volume')
plt.show()

df['MA20'] = df['Close'].rolling(20).mean()
df['MA50'] = df['Close'].rolling(50).mean()
plt.plot(df['Date'], df['Close'], label='Closing Price')
plt.plot(df['Date'], df['MA20'], label='20-Day MA')
plt.plot(df['Date'], df['MA50'], label='50-Day MA')

plt.xlabel('Date')
plt.ylabel('Price')
plt.title('AAPL Closing Price with Moving Averages')
plt.legend()
plt.show()